[package]
name = "guessing_game"
version = "0.1.0"
edition = "2021"
authors = ["Lee Jeongwoo<awmaker@kakao.com>"]
rust-version = "1.58.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
